### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Khamulus** [devlooped/Schematron#6]
Hi Daniel,

we plan to use the schematron nuget in our software but we do not find any licensing informations. 
Could you tell us under which license this software is released?

Regards
Bernhard Rosenberger

[![Back this issue](https://sponsorlink.blob.core.windows.net/public/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Added the missing MIT license. Thanks for bringing it up!
